api_version = "2025-04"

[[extensions]]
name = "t:name"
description = "t:description"
handle = "klaviyo-discount-ui"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.jsx"
target = "admin.discount-details.function-settings.render"


